### ISSUE TITLE
Create a public release of version 0.2.7 available at Maven Central

### ISSUE THREAD

**Issue by jonolehagemo** [statisticsnorway/json-stat.java#30]
Will the release of version 0.2.7 be available on Maven Central soon?
The available version of 0.2.3 has vulnerabilities in its dependencies.
The code in develop and master has fixed these vulnerabilities.

I see that the current CI-pipeline has ceased.

Message from Travis:
Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

**Comment by johnksv** [comment]
Version 0.2.8 is now available on Maven Central: https://central.sonatype.com/artifact/no.ssb.jsonstat/json-stat-java/0.2.8
This release is the same as 0.2.7 featurewise.
